name: Auto Label GSSoC

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

# We need write permissions to add labels to issues and PRs
permissions:
  issues: write
  pull-requests: write

jobs:
  apply-label:
    name: Apply gssoc-26 label
    runs-on: ubuntu-latest
    steps:
      - name: Add label
        uses: actions/github-script@v7
        with:
          script: |
            // In GitHub API, Pull Requests are treated as Issues for labels
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['gssoc-26', 'mentor:arpittkhandelwal']
            })
